Completed migration
CS320S22T3/taskbox pull request #50
Opened 2022-03-30 00:18 UTC by aasthapatil

2022-03-30 16:23 UTC, benmelz commented on server/db/migrations/20220329203243_init.js
> +};
The content you add here should actually live in another new migration file that you have to generate (by running something like `npx knex migrate:make create_companies`). The content mostly will be the same as here, except instead of recreating the users table, you will have to _alter_ the existing table to add the `company_id` column.

2022-04-04 04:04 UTC, aasthapatil commented on server/db/migrations/20220329203243_init.js
> +};
Right, I added the changes!

2022-04-06 16:13 UTC, sselkef commented
Sorry I still don't know how git works but an issue I encountered while trying to migrate your companies table was that it didn't return a promise so it didn't actually migrate the tables. The latest commit I made should fix that.

2022-04-06 16:23 UTC, sselkef submitted a review, later dismissed
Oh oops. I now see that I was supposed to request a change.
Companies table migration works and users table does update.

2022-04-07 17:39 UTC, matt532 approved these changes

2022-04-07 17:47 UTC, benmelz requested changes

2022-04-07 17:47 UTC, benmelz commented on server/db/migrations/20220404035348_create_companies.js
> +      t.integer("company_id").unsigned();
```suggestion
      t.integer("company_id").unsigned().notNullable();
```

2022-04-07 17:47 UTC, benmelz commented on server/db/seeds/default.js
> +  await knex("companies").insert([
```suggestion
  const companies = await knex("companies").insert([
```

2022-04-07 17:47 UTC, benmelz commented on server/db/seeds/default.js
> +    { company_id: 1, email: "hongxiang@email.com", password_digest: bcrypt.hashSync("password") },
```suggestion
    { company_id: companies[0].id, email: "ben@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: companies[0].id, email: "daniel@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "ava@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "matt@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "long@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "rohit@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "navid@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "aastha@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "jeet@email.com", password_digest: bcrypt.hashSync("password") },
    { company_id: 1, email: "hongxiang@email.com", password_digest: bcrypt.hashSync("password") },
```

2022-04-07 17:47 UTC, benmelz commented on server/db/seeds/default.js
> +    { company_id: 1, email: "hongxiang@email.com", password_digest: bcrypt.hashSync("password") },
I didn't do them all but you get the idea

2022-04-11 19:24 UTC, merged