Create database table for user_informations.
CS320S22T3/taskbox pull request #68
Opened 2022-04-10 20:42 UTC by louie7679

2022-04-11 01:02 UTC, daniel-melanson commented on server/db/migrations/20220328193739_create_users.js
>   * @param { import("knex").Knex } knex
See: https://github.com/CS320S22T3/taskbox/pull/50#discussion_r838738579

2022-04-11 01:04 UTC, daniel-melanson commented on server/src/pool.ts
> -export default knex(config);
The `pool.ts` file is responsible for creating and exporting a global instance of `knex` for the rest of the project to use. Removing this will break the project.

2022-04-11 01:22 UTC, daniel-melanson commented on server/db/seeds/default.js
> +  await knew("user_information").del();
`knew` -> `knex`

2022-04-11 01:30 UTC, daniel-melanson commented on server/db/migrations/20220328193739_create_users.js
> +    t.boolean("is_manager")
Do these need to be non-nullable?

2022-04-11 01:32 UTC, daniel-melanson commented on server/db/seeds/default.js
>  exports.seed = async function (knex) {
This will probably need to be changed whenever the first migration gets pulled.

2022-04-11 01:32 UTC, daniel-melanson commented on server/db/seeds/default.js
>  exports.seed = async function (knex) {
(Entire file)

2022-04-11 01:35 UTC, daniel-melanson commented on server/db/migrations/20220328193739_create_users.js
> +    t.integer("user_id").unsigned();
Needs to reference user id?

2022-04-11 01:36 UTC, daniel-melanson commented on server/db/migrations/20220328193739_create_users.js
> +  })
Should be left to the companies migration pr #50

2022-04-20 20:40 UTC, daniel-melanson commented on package.json
> +{
Seems like you accidentally made a `package.json` in the root directory.

2022-04-20 20:46 UTC, daniel-melanson commented on server/db/migrations/20220328193739_create_users.js
> + exports.up = function (knex) {
```suggestion
exports.up = function (knex) {
```

2022-04-20 20:48 UTC, daniel-melanson commented on server/db/seeds/default.js
> +        last_name: 'Jordan',
```suggestion
        first_name: "Ben", 
        last_name: "Melz, 
```

2022-04-20 20:49 UTC, daniel-melanson commented on server/db/seeds/default.js
> +        last_name: 'Edwards',
```suggestion
        first_name: "Daniel", 
        last_name: "Melanson", 
```

2022-04-20 20:49 UTC, daniel-melanson commented on server/src/pool.ts
> +export default knex(config);
```suggestion
export default knex(config);

```

2022-04-20 20:50 UTC, daniel-melanson commented on server/db/seeds/default.js
> +        date_hired: '3-27/-019',
```suggestion
        date_hired: '3-27-019', 
```

2022-04-20 20:50 UTC, daniel-melanson commented on server/src/pool.ts
> +  interface UserInformations {
```suggestion
  interface UserInformation {
```

2022-04-21 02:39 UTC, daniel-melanson commented on server/db/migrations/20220411191207_create_user_informations.js
> +        t.boolean("is_manager");
One last thing, I think these should be non-nullable. Just chain `.nonNullable()` after each.

2022-04-24 19:13 UTC, benmelz requested changes
No need to add a `user_id` column to `users` - it already exists as `users.id`

2022-04-24 19:13 UTC, benmelz commented on server/db/migrations/20220411191207_create_user_informations.js
> +    })
```suggestion
```

2022-04-24 19:13 UTC, benmelz commented on server/db/migrations/20220411191207_create_user_informations.js
> +    });
```suggestion
```

2022-04-25 08:48 UTC, daniel-melanson approved these changes

2022-04-25 18:30 UTC, Fish7793 approved these changes

2022-04-25 18:32 UTC, benmelz requested changes
Table names should be plural - I'll override and merge once these are updated

2022-04-25 18:32 UTC, benmelz commented on server/db/migrations/20220411191207_create_user_informations.js
> +  return knex.schema.createTable("user_information", (t) => {
```suggestion
  return knex.schema.createTable("user_informations", (t) => {
```

2022-04-25 18:32 UTC, benmelz commented on server/db/migrations/20220411191207_create_user_informations.js
> +  knex.schema.dropTable("user_information");
```suggestion
  knex.schema.dropTable("user_informations");
```

2022-04-25 18:32 UTC, benmelz commented on server/db/seeds/default.js
> +  await knex("user_information").del();
```suggestion
  await knex("user_informations").del();
```

2022-04-25 18:32 UTC, benmelz commented on server/db/seeds/default.js
> +  const userinfo = await knex("user_information").insert(
```suggestion
  const userinfo = await knex("user_informations").insert(
```

2022-04-25 19:16 UTC, merged