Time off table
CS320S22T3/taskbox pull request #73
Opened 2022-04-11 19:49 UTC by jeetmitra01

time_off_requests table has been added with a few seeds

2022-04-24 19:54 UTC, benmelz requested changes

2022-04-24 19:54 UTC, benmelz commented on server/db/seeds/default.js
> +
```suggestion
```

2022-04-24 19:54 UTC, benmelz commented on server/db/seeds/default.js
> -    "*"
If I remember right, this important so that `companies` actually gets populated with the created data. Was this causing issues for you?

2022-04-24 19:54 UTC, benmelz commented on server/db/seeds/default.js
> +  const time_off_requests = await knex("time_off_requests").insert([
`time_off_request` records should always be tied to a `task` - i.e. this should be moved above `const tasks = `, and the first task (the one with `info_type: "time_off_requests"` should be adjusted to use `time_off_requests[0].id for its `info_id`).

2022-04-24 19:54 UTC, benmelz commented on server/db/seeds/default.js
> +  const time_off_requests = await knex("time_off_requests").insert([
Furthermore we only really need the first time off request here since otherwise you would have to add tasks for the other 3.

2022-04-25 14:03 UTC, sselkef approved these changes
I had to manually create the database for some reason because "npm run db:create" wasn't working in this branch, but other than that the table was created successfully and the seed was inserted. Nice job.

2022-04-25 19:04 UTC, hongxiangwan approved these changes

2022-04-25 19:05 UTC, merged