Task data layer
CS320S22T3/taskbox pull request #87
Opened 2022-04-25 19:51 UTC by absmith22

The render is still fairly empty without another component to display the tasks.

2022-04-25 21:27 UTC, absmith22 commented
Failing lint due to a server-side file (tasks.route.ts) that does not use a number of its imports

2022-05-02 19:19 UTC, benmelz requested changes

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +  async create_task(data: any) {
```suggestion
  async createTask(data: any) {
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +  async update_task(data: any) {
```suggestion
  async updateTask(data: any) {
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +      const res = await fetch("/api/sessions", {
```suggestion
      const res = await fetch("/api/tasks", {
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +    return fetch("/api/users", {
```suggestion
    return fetch(`/api/users/${this.props.userId}/tasks`, {
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +      body: JSON.stringify({ userId }),
```suggestion
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +      const res = await fetch("api/tasks", {
```suggestion
      const res = await fetch(`/api/tasks/${data.id}`, {
```

2022-05-02 19:19 UTC, benmelz commented on client/src/components/TaskLayer.tsx
> +          create_task: this.create_task,
```suggestion
          tasks: this.state.tasks,
          create_task: this.create_task,
```

2022-05-06 15:57 UTC, merged